package com.workflow.embed.infrastructure.persistence.record;

import java.time.LocalDateTime;

/** Flat MyBatis projection for the launch configuration aggregate. */
public record EmbedLaunchConfigurationRow(
        String applicationId,
        String applicationStatus,
        LocalDateTime applicationExpiresAt,
        long applicationVersion,
        String viewId,
        String viewKey,
        String viewSurfaceType,
        String viewStatus,
        String publishedReleaseId,
        long viewSecurityVersion,
        String releaseId,
        long releaseRevision,
        String releaseSurfaceType,
        String entryModesJson,
        String releaseCapabilitiesJson,
        String contextSchemaJson,
        String uiConfigJson,
        String grantId,
        String grantStatus,
        boolean trustedSubjectAssertion,
        String capabilityCeilingJson,
        int maxActiveSessionsPerUser,
        int maxSessionSeconds,
        int launchLimitPerMinute,
        int runtimeLimitPerMinute,
        int maxConcurrency,
        LocalDateTime grantExpiresAt,
        long grantSecurityVersion,
        String providerId,
        String providerType,
        String providerStatus,
        String providerIssuer,
        String subjectNamespace,
        String audiencesJson,
        String algorithmsJson,
        String jwksMode,
        String jwksJson,
        String jwksUrl,
        int clockSkewSeconds,
        int maxAssertionLifetimeSeconds,
        long providerKeyVersion,
        long providerSecurityVersion) {
}
