package com.workflow.embed.infrastructure.persistence.record;

import java.time.LocalDateTime;

/** Flat Session plus live security-source projection. */
public record EmbedSessionSecurityRow(
        String id,
        String sessionTokenDigest,
        String applicationId,
        String grantId,
        String viewId,
        String viewReleaseId,
        String identityProviderId,
        long providerSecurityVersion,
        String flowUserId,
        String flowUsername,
        String identityBindingId,
        String parentOrigin,
        String channelId,
        String entryMode,
        String recordId,
        String contextCiphertext,
        String contextCipherKeyVersion,
        String capabilitySnapshotJson,
        long applicationVersion,
        long grantSecurityVersion,
        long viewSecurityVersion,
        long bindingVersion,
        String sessionStatus,
        boolean slotReleased,
        LocalDateTime lastSeenAt,
        LocalDateTime idleExpiresAt,
        LocalDateTime absoluteExpiresAt,
        String applicationStatus,
        LocalDateTime applicationExpiresAt,
        long currentApplicationVersion,
        String grantStatus,
        LocalDateTime grantExpiresAt,
        long currentGrantSecurityVersion,
        String viewStatus,
        long currentViewSecurityVersion,
        String providerStatus,
        long currentProviderSecurityVersion,
        String bindingStatus,
        String currentBindingApplicationId,
        String currentBindingIdentityProviderId,
        String currentBindingFlowUserId,
        LocalDateTime bindingEffectiveAt,
        LocalDateTime bindingExpiresAt,
        long currentBindingVersion,
        String flowUserStatus,
        int flowUserDeleted,
        int flowUserPasswordResetRequired) {
}
