package com.workflow.embed.domain;

/** Stable public error codes for the Embed launch and session boundary. */
public enum EmbedErrorCode {
    INVALID_REQUEST,
    EMBED_CONTEXT_INVALID,
    EMBED_VIEW_NOT_GRANTED,
    EMBED_ORIGIN_NOT_ALLOWED,
    EMBED_IDENTITY_ASSERTION_INVALID,
    EMBED_IDENTITY_ASSERTION_REPLAYED,
    EXTERNAL_IDENTITY_NOT_MAPPED,
    FLOW_USER_DISABLED,
    EMBED_VIEW_DISABLED,
    EMBED_OPERATION_NOT_ALLOWED,
    EMBED_LAUNCH_INVALID,
    EMBED_LAUNCH_EXPIRED,
    EMBED_SESSION_INVALID,
    EMBED_SESSION_EXPIRED,
    EMBED_SESSION_REVOKED,
    EMBED_SESSION_LIMIT_EXCEEDED,
    RATE_LIMIT_EXCEEDED,
    EMBED_RESOURCE_NOT_FOUND,
    EMBED_IDEMPOTENCY_KEY_REUSED,
    EMBED_REQUEST_IN_PROGRESS,
    FORM_VALIDATION_FAILED,
    EMBED_RECORD_CONFLICT,
    EMBED_RUNTIME_UNAVAILABLE
}
