-- 修复 V001 中缺失的表（Flyway 首次执行时中断导致）
-- 缺失表列表：entity_relation, process_cc_record, process_common_opinion,
-- process_draft, process_task_instance

CREATE TABLE `entity_relation` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `parent_entity_id` varchar(64) NOT NULL COMMENT '主实体ID',
  `parent_entity_code` varchar(100) NOT NULL COMMENT '主实体编码',
  `parent_field_id` varchar(64) DEFAULT NULL COMMENT '主实体关系字段ID',
  `parent_field_code` varchar(100) NOT NULL COMMENT '主实体关系字段编码',
  `relation_code` varchar(100) NOT NULL COMMENT '关系编码',
  `relation_name` varchar(200) DEFAULT NULL COMMENT '关系名称',
  `child_entity_id` varchar(64) NOT NULL COMMENT '子实体ID',
  `child_entity_code` varchar(100) NOT NULL COMMENT '子实体编码',
  `child_ref_field_code` varchar(100) NOT NULL COMMENT '子实体回填主数据ID字段',
  `relation_type` varchar(20) NOT NULL DEFAULT 'ONE_TO_MANY' COMMENT '关系类型：ONE_TO_ONE/ONE_TO_MANY',
  `cascade_delete` tinyint DEFAULT '1' COMMENT '主数据删除时是否级联删除子数据',
  `required` tinyint DEFAULT '0' COMMENT '是否必填',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `enabled` tinyint DEFAULT '1' COMMENT '是否启用',
  `deleted` tinyint DEFAULT '0' COMMENT '是否删除',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_parent_field` (`parent_entity_id`,`parent_field_code`),
  KEY `idx_parent_entity` (`parent_entity_id`,`enabled`,`deleted`),
  KEY `idx_parent_code` (`parent_entity_code`,`enabled`,`deleted`),
  KEY `idx_child_entity` (`child_entity_id`),
  KEY `idx_relation_code` (`relation_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='实体关系定义表';

CREATE TABLE `process_cc_record` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `process_instance_id` varchar(64) NOT NULL COMMENT '流程实例ID',
  `process_definition_id` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `process_key` varchar(100) DEFAULT NULL COMMENT '流程Key',
  `process_name` varchar(200) DEFAULT NULL COMMENT '流程名称',
  `business_key` varchar(200) DEFAULT NULL COMMENT '业务Key',
  `node_id` varchar(100) DEFAULT NULL COMMENT '节点ID',
  `node_name` varchar(200) DEFAULT NULL COMMENT '节点名称',
  `cc_user_id` varchar(64) DEFAULT NULL COMMENT '抄送人ID',
  `cc_user_name` varchar(100) DEFAULT NULL COMMENT '抄送人名称',
  `cc_type` varchar(20) DEFAULT 'AUTO' COMMENT '抄送类型：AUTO自动/MANUAL手动',
  `cc_timing` varchar(20) DEFAULT NULL COMMENT '抄送时机',
  `read_status` varchar(20) DEFAULT 'UNREAD' COMMENT '阅读状态：UNREAD未读/READ已读',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `deleted` tinyint DEFAULT '0' COMMENT '是否删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_process_instance` (`process_instance_id`),
  KEY `idx_cc_user` (`cc_user_id`,`read_status`),
  KEY `idx_process_key` (`process_key`),
  KEY `idx_deleted` (`deleted`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='流程抄送记录表';

CREATE TABLE `process_common_opinion` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID',
  `opinion_content` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '意见内容',
  `opinion_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'APPROVE' COMMENT '意见类型：APPROVE同意/REJECT驳回/TRANSFER转办',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `use_count` int DEFAULT '0' COMMENT '使用次数',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='常用审批意见';

CREATE TABLE `process_draft` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `draft_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '草稿编码',
  `process_definition_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程定义ID',
  `process_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程名称',
  `entity_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体编码',
  `entity_data_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体数据ID（临时数据）',
  `business_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务主键',
  `form_data` json NOT NULL COMMENT '表单数据',
  `draft_title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '草稿标题',
  `draft_summary` text COLLATE utf8mb4_unicode_ci COMMENT '草稿摘要',
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创建人ID',
  `user_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE有效/SUBMITTED已提交/DELETED已删除',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `draft_code` (`draft_code`),
  KEY `idx_user` (`user_id`,`status`,`updated_at`),
  KEY `idx_process` (`process_definition_id`),
  KEY `idx_entity` (`entity_code`,`entity_data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程草稿箱';

CREATE TABLE `process_task_instance` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务实例ID',
  `process_instance_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流程实例ID',
  `task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flowable任务ID',
  `task_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务节点Key',
  `task_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
  `process_definition_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程定义ID',
  `process_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程名称',
  `entity_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体编码',
  `entity_data_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体数据ID',
  `business_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务主键',
  `assignee_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被指派人ID',
  `assignee_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被指派人姓名',
  `owner_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务所有人ID',
  `candidate_users` text COLLATE utf8mb4_unicode_ci COMMENT '候选人ID列表（JSON）',
  `candidate_groups` text COLLATE utf8mb4_unicode_ci COMMENT '候选组列表（JSON）',
  `task_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务类型：TODO待办/DONE已办/DRAFT草稿/CC抄送',
  `action_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作类型：SUBMIT/APPROVE/REJECT/TRANSFER/RETURN/DELEGATE',
  `action_comment` text COLLATE utf8mb4_unicode_ci COMMENT '处理意见',
  `form_data` json DEFAULT NULL COMMENT '表单数据快照',
  `due_time` datetime DEFAULT NULL COMMENT '截止时间',
  `priority` int DEFAULT '50' COMMENT '优先级 0-100',
  `is_read` tinyint DEFAULT '0' COMMENT '是否已读',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `start_time` datetime DEFAULT NULL COMMENT '任务开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '任务结束时间',
  `duration_ms` bigint DEFAULT NULL COMMENT '处理耗时（毫秒）',
  `parent_task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父任务ID（用于会签）',
  `root_task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '根任务ID',
  `delegation_state` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '委托状态：PENDING/RESOLVED',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_process_instance` (`process_instance_id`),
  KEY `idx_assignee_type` (`assignee_id`,`task_type`),
  KEY `idx_entity` (`entity_code`,`entity_data_id`),
  KEY `idx_business_key` (`business_key`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_due_time` (`due_time`),
  KEY `idx_task_type` (`task_type`,`is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程任务实例表';
