-- 修复 V001 中缺失的表（Flyway 首次执行时中断导致）
-- 缺失表列表：entity_relation, process_cc_record, process_common_opinion,
-- process_draft, process_task_instance, report_category, report_dataset,
-- report_definition, report_schedule, service_category, service_definition,
-- service_execution_log, service_node, view_button_config, view_definition,
-- view_field_config, view_query_config

CREATE TABLE `entity_relation` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `parent_entity_id` varchar(64) NOT NULL COMMENT '主实体ID',
  `parent_entity_code` varchar(100) NOT NULL COMMENT '主实体编码',
  `parent_field_id` varchar(64) DEFAULT NULL COMMENT '主实体关系字段ID',
  `parent_field_code` varchar(100) NOT NULL COMMENT '主实体关系字段编码',
  `relation_code` varchar(100) NOT NULL COMMENT '关系编码',
  `relation_name` varchar(200) DEFAULT NULL COMMENT '关系名称',
  `child_entity_id` varchar(64) NOT NULL COMMENT '子实体ID',
  `child_entity_code` varchar(100) NOT NULL COMMENT '子实体编码',
  `child_ref_field_code` varchar(100) NOT NULL COMMENT '子实体回填主数据ID字段',
  `relation_type` varchar(20) NOT NULL DEFAULT 'ONE_TO_MANY' COMMENT '关系类型：ONE_TO_ONE/ONE_TO_MANY',
  `cascade_delete` tinyint DEFAULT '1' COMMENT '主数据删除时是否级联删除子数据',
  `required` tinyint DEFAULT '0' COMMENT '是否必填',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `enabled` tinyint DEFAULT '1' COMMENT '是否启用',
  `deleted` tinyint DEFAULT '0' COMMENT '是否删除',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_parent_field` (`parent_entity_id`,`parent_field_code`),
  KEY `idx_parent_entity` (`parent_entity_id`,`enabled`,`deleted`),
  KEY `idx_parent_code` (`parent_entity_code`,`enabled`,`deleted`),
  KEY `idx_child_entity` (`child_entity_id`),
  KEY `idx_relation_code` (`relation_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='实体关系定义表';

CREATE TABLE `process_cc_record` (
  `id` varchar(64) NOT NULL COMMENT '主键ID',
  `process_instance_id` varchar(64) NOT NULL COMMENT '流程实例ID',
  `process_definition_id` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `process_key` varchar(100) DEFAULT NULL COMMENT '流程Key',
  `process_name` varchar(200) DEFAULT NULL COMMENT '流程名称',
  `business_key` varchar(200) DEFAULT NULL COMMENT '业务Key',
  `node_id` varchar(100) DEFAULT NULL COMMENT '节点ID',
  `node_name` varchar(200) DEFAULT NULL COMMENT '节点名称',
  `cc_user_id` varchar(64) DEFAULT NULL COMMENT '抄送人ID',
  `cc_user_name` varchar(100) DEFAULT NULL COMMENT '抄送人名称',
  `cc_type` varchar(20) DEFAULT 'AUTO' COMMENT '抄送类型：AUTO自动/MANUAL手动',
  `cc_timing` varchar(20) DEFAULT NULL COMMENT '抄送时机',
  `read_status` varchar(20) DEFAULT 'UNREAD' COMMENT '阅读状态：UNREAD未读/READ已读',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `deleted` tinyint DEFAULT '0' COMMENT '是否删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_process_instance` (`process_instance_id`),
  KEY `idx_cc_user` (`cc_user_id`,`read_status`),
  KEY `idx_process_key` (`process_key`),
  KEY `idx_deleted` (`deleted`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='流程抄送记录表';

CREATE TABLE `process_common_opinion` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID',
  `opinion_content` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '意见内容',
  `opinion_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'APPROVE' COMMENT '意见类型：APPROVE同意/REJECT驳回/TRANSFER转办',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `use_count` int DEFAULT '0' COMMENT '使用次数',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='常用审批意见';

CREATE TABLE `process_draft` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `draft_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '草稿编码',
  `process_definition_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程定义ID',
  `process_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程名称',
  `entity_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体编码',
  `entity_data_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体数据ID（临时数据）',
  `business_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务主键',
  `form_data` json NOT NULL COMMENT '表单数据',
  `draft_title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '草稿标题',
  `draft_summary` text COLLATE utf8mb4_unicode_ci COMMENT '草稿摘要',
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '创建人ID',
  `user_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE有效/SUBMITTED已提交/DELETED已删除',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `draft_code` (`draft_code`),
  KEY `idx_user` (`user_id`,`status`,`updated_at`),
  KEY `idx_process` (`process_definition_id`),
  KEY `idx_entity` (`entity_code`,`entity_data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程草稿箱';

CREATE TABLE `process_task_instance` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务实例ID',
  `process_instance_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流程实例ID',
  `task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flowable任务ID',
  `task_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务节点Key',
  `task_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
  `process_definition_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程定义ID',
  `process_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '流程名称',
  `entity_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体编码',
  `entity_data_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体数据ID',
  `business_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务主键',
  `assignee_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被指派人ID',
  `assignee_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被指派人姓名',
  `owner_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务所有人ID',
  `candidate_users` text COLLATE utf8mb4_unicode_ci COMMENT '候选人ID列表（JSON）',
  `candidate_groups` text COLLATE utf8mb4_unicode_ci COMMENT '候选组列表（JSON）',
  `task_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务类型：TODO待办/DONE已办/DRAFT草稿/CC抄送',
  `action_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作类型：SUBMIT/APPROVE/REJECT/TRANSFER/RETURN/DELEGATE',
  `action_comment` text COLLATE utf8mb4_unicode_ci COMMENT '处理意见',
  `form_data` json DEFAULT NULL COMMENT '表单数据快照',
  `due_time` datetime DEFAULT NULL COMMENT '截止时间',
  `priority` int DEFAULT '50' COMMENT '优先级 0-100',
  `is_read` tinyint DEFAULT '0' COMMENT '是否已读',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `start_time` datetime DEFAULT NULL COMMENT '任务开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '任务结束时间',
  `duration_ms` bigint DEFAULT NULL COMMENT '处理耗时（毫秒）',
  `parent_task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父任务ID（用于会签）',
  `root_task_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '根任务ID',
  `delegation_state` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '委托状态：PENDING/RESOLVED',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_process_instance` (`process_instance_id`),
  KEY `idx_assignee_type` (`assignee_id`,`task_type`),
  KEY `idx_entity` (`entity_code`,`entity_data_id`),
  KEY `idx_business_key` (`business_key`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_due_time` (`due_time`),
  KEY `idx_task_type` (`task_type`,`is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程任务实例表';

CREATE TABLE `report_category` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '0',
  `category_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_order` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `category_code` (`category_code`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报表分类';

CREATE TABLE `report_dataset` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `report_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dataset_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dataset_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dataset_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '数据集类型：SQL/ENTITY/API',
  `source_config` json NOT NULL COMMENT '数据源配置',
  `field_mappings` json DEFAULT NULL COMMENT '字段映射',
  `cache_config` json DEFAULT NULL COMMENT '缓存配置',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_report` (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报表数据集';

CREATE TABLE `report_definition` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报表ID',
  `report_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报表编码',
  `report_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报表名称',
  `report_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报表类型：TABLE表格/CHART图表/DASHBOARD大屏/PRINT打印',
  `category_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报表分类ID',
  `dataset_config` json DEFAULT NULL COMMENT '数据集配置（支持多数据集）',
  `layout_config` json NOT NULL COMMENT '报表布局配置',
  `params_config` json DEFAULT NULL COMMENT '报表参数配置',
  `style_config` json DEFAULT NULL COMMENT '样式配置',
  `permission_config` json DEFAULT NULL COMMENT '权限配置',
  `version` int DEFAULT '1' COMMENT '版本号',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '状态',
  `created_by` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `report_code` (`report_code`),
  KEY `idx_category` (`category_id`),
  KEY `idx_code` (`report_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报表定义表';

CREATE TABLE `report_schedule` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `report_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `schedule_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cron_expression` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `param_values` json DEFAULT NULL COMMENT '参数值',
  `export_format` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'EXCEL' COMMENT '导出格式',
  `notify_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'EMAIL' COMMENT '通知类型',
  `notify_targets` text COLLATE utf8mb4_unicode_ci COMMENT '通知目标',
  `last_run_time` datetime DEFAULT NULL,
  `next_run_time` datetime DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ENABLED',
  `created_by` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_report` (`report_id`),
  KEY `idx_next_run` (`next_run_time`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报表定时任务';

CREATE TABLE `service_category` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '0',
  `category_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_order` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `category_code` (`category_code`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务分类表';

CREATE TABLE `service_definition` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '服务ID',
  `service_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '服务编码',
  `service_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '服务名称',
  `service_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ORCHESTRATION' COMMENT '服务类型：ORCHESTRATION编排/SCRIPT脚本/PROXY代理',
  `category_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分类ID',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT '服务描述',
  `input_params` json DEFAULT NULL COMMENT '输入参数定义',
  `output_params` json DEFAULT NULL COMMENT '输出参数定义',
  `flow_config` json DEFAULT NULL COMMENT '流程配置（DAG）',
  `variables` json DEFAULT NULL COMMENT '变量定义',
  `timeout_ms` int DEFAULT '30000' COMMENT '超时时间（毫秒）',
  `retry_config` json DEFAULT NULL COMMENT '重试配置',
  `exception_handler` json DEFAULT NULL COMMENT '异常处理配置',
  `version` int DEFAULT '1' COMMENT '版本号',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '状态',
  `created_by` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `service_code` (`service_code`),
  KEY `idx_code` (`service_code`),
  KEY `idx_category` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务定义表';

CREATE TABLE `service_execution_log` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `service_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '服务ID',
  `execution_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '执行实例ID',
  `trigger_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '触发类型：MANUAL手动/SCHEDULE定时/EVENT事件/API接口',
  `trigger_source` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '触发来源',
  `input_params` text COLLATE utf8mb4_unicode_ci COMMENT '输入参数',
  `output_result` text COLLATE utf8mb4_unicode_ci COMMENT '输出结果',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '状态：RUNNING运行中/SUCCESS成功/FAILED失败/TIMEOUT超时',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_ms` int DEFAULT NULL COMMENT '执行耗时（毫秒）',
  `node_executions` json DEFAULT NULL COMMENT '节点执行详情',
  `error_message` text COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_service` (`service_id`,`start_time`),
  KEY `idx_execution` (`execution_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务执行记录表';

CREATE TABLE `service_node` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `service_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '服务ID',
  `node_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点唯一标识',
  `node_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点类型：START/END/ENTITY_CRUD/HTTP/SQL/SCRIPT/CONDITION/PARALLEL/JOIN/LOOP/SUBFLOW/PROCESS/MESSAGE/DELAY/MAPPING/LOG',
  `node_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '节点名称',
  `position_x` decimal(10,2) DEFAULT NULL COMMENT '画布X坐标',
  `position_y` decimal(10,2) DEFAULT NULL COMMENT '画布Y坐标',
  `config` json NOT NULL COMMENT '节点配置',
  `input_mapping` json DEFAULT NULL COMMENT '输入参数映射',
  `output_mapping` json DEFAULT NULL COMMENT '输出参数映射',
  `next_nodes` json DEFAULT NULL COMMENT '下游节点ID列表',
  `condition_expression` text COLLATE utf8mb4_unicode_ci COMMENT '条件表达式',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_node` (`service_id`,`node_id`),
  KEY `idx_service` (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='服务节点表';

CREATE TABLE `view_button_config` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `view_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `button_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `button_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `button_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '按钮位置：TOOLBAR工具栏/ROW行操作/BATCH批量操作',
  `action_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '动作类型',
  `action_config` json DEFAULT NULL COMMENT '动作配置',
  `icon` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `style` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '样式',
  `sort_order` int DEFAULT '0',
  `visible_condition` text COLLATE utf8mb4_unicode_ci COMMENT '显示条件',
  `permission_code` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '权限标识',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_view` (`view_id`,`button_type`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视图按钮配置表';

CREATE TABLE `view_definition` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '视图ID',
  `view_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '视图编码',
  `view_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '视图名称',
  `view_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '视图类型：LIST列表/CHART图表/DASHBOARD看板/DETAIL详情',
  `entity_code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联实体编码',
  `data_source_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ENTITY' COMMENT '数据源类型：ENTITY/SQL/API',
  `data_source_config` json DEFAULT NULL COMMENT '数据源配置',
  `layout_config` json DEFAULT NULL COMMENT '布局配置',
  `style_config` json DEFAULT NULL COMMENT '样式配置',
  `is_default` tinyint DEFAULT '0' COMMENT '是否默认视图',
  `version` int DEFAULT '1' COMMENT '版本号',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'ACTIVE' COMMENT '状态',
  `created_by` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `view_code` (`view_code`),
  KEY `idx_entity` (`entity_code`),
  KEY `idx_code` (`view_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视图定义表';

CREATE TABLE `view_field_config` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `view_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '字段编码',
  `field_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '字段显示名',
  `field_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '字段类型',
  `sort_order` int DEFAULT '0' COMMENT '显示顺序',
  `width` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '列宽',
  `align` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'left' COMMENT '对齐方式',
  `is_show` tinyint DEFAULT '1' COMMENT '是否显示',
  `is_sortable` tinyint DEFAULT '0' COMMENT '是否可排序',
  `is_searchable` tinyint DEFAULT '0' COMMENT '是否可搜索',
  `formatter_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '格式化类型',
  `formatter_config` json DEFAULT NULL COMMENT '格式化配置',
  `fixed` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '固定列',
  `show_in_list` tinyint DEFAULT '1',
  `show_in_detail` tinyint DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_view` (`view_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视图字段配置表';

CREATE TABLE `view_query_config` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `view_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_code` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `query_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '查询类型：EQ/LIKE/BETWEEN等',
  `component_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '组件类型',
  `component_config` json DEFAULT NULL COMMENT '组件配置',
  `default_value` text COLLATE utf8mb4_unicode_ci COMMENT '默认值',
  `placeholder` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` int DEFAULT '0',
  `is_advanced` tinyint DEFAULT '0' COMMENT '是否高级查询',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_view` (`view_id`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视图查询条件配置表';
