import './styles/theme.css'
export const MOBILE_UI_VERSION = '1.0.0'
export { default as MobileTaskCard } from './workflow/MobileTaskCard.vue'
export { default as MobileFormRenderer } from './form/MobileFormRenderer.vue'
export { default as MobileReadonlyField } from './fields/MobileReadonlyField.vue'
export { default as MobileUserPicker } from './pickers/MobileUserPicker.vue'
export { default as MobileApprovalPanel } from './workflow/MobileApprovalPanel.vue'
export { default as MobileActionBar } from './workflow/MobileActionBar.vue'
export { default as MobileProcessProgress } from './workflow/MobileProcessProgress.vue'
export { default as MobileApprovalHistory } from './workflow/MobileApprovalHistory.vue'
export { registerMobileExtension, getMobileExtension, mobileFieldCapability } from './fields/registry.js'
export { default as MobileFieldRenderer } from './fields/MobileFieldRenderer.vue'
