ALTER TABLE `ui_data_source_definition`
  MODIFY COLUMN `source_type` varchar(30)
  COLLATE utf8mb4_unicode_ci NOT NULL
  COMMENT 'DICTIONARY/STATIC_OPTIONS/REGISTERED_PROVIDER/INTEGRATION_CONNECTOR/RUNTIME_CONTEXT/STRUCTURED_COMPUTE';
