CREATE TABLE IF NOT EXISTS `entity_publish_history` (
  `id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `entity_id` VARCHAR(64) NOT NULL COMMENT '实体定义ID',
  `entity_code` VARCHAR(100) NOT NULL COMMENT '实体编码',
  `entity_name` VARCHAR(200) NOT NULL COMMENT '实体名称',
  `process_definition_id` VARCHAR(64) DEFAULT NULL COMMENT '发布时绑定流程定义ID',
  `version` INT NOT NULL COMMENT '版本号',
  `version_description` VARCHAR(500) DEFAULT NULL COMMENT '版本描述',
  `fields_snapshot` LONGTEXT DEFAULT NULL COMMENT '字段定义快照JSON',
  `table_ddl` LONGTEXT DEFAULT NULL COMMENT '表结构DDL',
  `publish_type` VARCHAR(20) NOT NULL COMMENT '发布类型',
  `changes_description` VARCHAR(1000) DEFAULT NULL COMMENT '变更描述',
  `published_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  `published_by` VARCHAR(64) DEFAULT NULL COMMENT '发布人ID',
  `published_by_name` VARCHAR(100) DEFAULT NULL COMMENT '发布人姓名',
  `status` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态',
  PRIMARY KEY (`id`),
  KEY `idx_entity_publish_history_entity` (`entity_id`, `version`),
  KEY `idx_entity_publish_history_code` (`entity_code`),
  KEY `idx_entity_publish_history_process` (`process_definition_id`),
  KEY `idx_entity_publish_history_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实体发布版本历史';
