package com.workflow.admin.identity.position.api;

/**
 * 职务管理 API 的稳定业务错误码。
 */
public enum PositionErrorCode {
    POSITION_NOT_FOUND,
    POSITION_CODE_DUPLICATED,
    POSITION_REFERENCED,
    POSITION_UNIT_TYPE_MISMATCH,
    POSITION_STATUS_INVALID,
    POSITION_HOLDER_MODE_CONFLICT,
    POSITION_REVISION_CONFLICT,
    ASSIGNMENT_NOT_FOUND,
    ASSIGNMENT_PERIOD_INVALID,
    ASSIGNMENT_PERIOD_OVERLAPPED,
    SINGLE_POSITION_OCCUPIED,
    PRIMARY_HOLDER_CONFLICT,
    ORGANIZATION_SCOPE_FORBIDDEN,
    ORGANIZATION_HIERARCHY_INVALID,
    ORGANIZATION_UNIT_NOT_FOUND,
    ORGANIZATION_UNIT_DISABLED,
    USER_NOT_FOUND,
    USER_DISABLED,
    ASSIGNMENT_REVISION_CONFLICT,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_KEY_REUSED,
    BATCH_ASSIGNMENT_INVALID
}
