{{- if .Values.server.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flow.fullname" . }}-server
  labels:
    {{- include "flow.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  minAvailable: {{ .Values.server.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "flow.componentLabels" (dict "root" . "component" "server") | nindent 6 }}
---
{{- end }}
{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flow.fullname" . }}-web
  labels:
    {{- include "flow.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "flow.componentLabels" (dict "root" . "component" "web") | nindent 6 }}
{{- end }}
