apiVersion: v1
kind: Service
metadata:
  name: {{ include "flow.fullname" . }}-server
  labels:
    {{- include "flow.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "flow.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9090
      targetPort: management
