apiVersion: v1
kind: Service
metadata:
  name: {{ include "flow.fullname" . }}-web
  labels:
    {{- include "flow.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "flow.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
