// Generated by scripts/generate-embed-sdk-types.mjs from docs/api/embed-v1.yaml.
// Do not edit manually. Run: npm run generate:embed-sdk-types

export const FLOW_EMBED_PROTOCOL: "flow-embed/1"
export const MAX_MESSAGE_BYTES: 262144

export const FLOW_EMBED_CAPABILITIES: readonly [
  "LIST_QUERY",
  "SELECTION_RETURN",
  "RECORD_VIEW",
  "RECORD_CREATE",
  "ACTION_EXECUTE",
]

export const FLOW_EMBED_COMMANDS: Readonly<{
  REFRESH: "refresh"
  SET_THEME: "set-theme"
  SET_LOCALE: "set-locale"
  FOCUS: "focus"
  DESTROY: "destroy"
}>

export const FLOW_EMBED_EVENTS: Readonly<{
  ACK: "ack"
  INITIALIZED: "initialized"
  RESIZE: "resize"
  SELECTION_CHANGED: "selection.changed"
  FORM_SAVED: "form.saved"
  ERROR: "error"
  SESSION_EXPIRED: "session.expired"
  NAVIGATION_REQUEST: "navigation.request"
  ACTION_STARTED: "action.started"
  ACTION_COMPLETED: "action.completed"
  CLOSE_REQUESTED: "close.requested"
}>

export type FlowEmbedCapability = typeof FLOW_EMBED_CAPABILITIES[number]
export type FlowEmbedCommand = typeof FLOW_EMBED_COMMANDS[keyof typeof FLOW_EMBED_COMMANDS]
export type FlowEmbedProtocolEventType = typeof FLOW_EMBED_EVENTS[keyof typeof FLOW_EMBED_EVENTS]
export type FlowEmbedEventType = FlowEmbedProtocolEventType | 'connected'

export type FlowEmbedJsonValue =
  | string
  | number
  | boolean
  | null
  | ReadonlyArray<FlowEmbedJsonValue>
  | { readonly [key: string]: FlowEmbedJsonValue }

export type FlowEmbedSurfaceType = "LIST" | "FORM"
export type FlowEmbedRecordId = string
export type FlowEmbedScalarValue = string | number | boolean | null
export type FlowEmbedClientValue = FlowEmbedScalarValue | ReadonlyArray<FlowEmbedScalarValue>
export type FlowEmbedProjectedValues = Record<string, FlowEmbedClientValue>
export interface HostRecordProjection {
  "id": FlowEmbedRecordId
  "values": FlowEmbedProjectedValues
}

export interface AckEventPayload {
  "command": "refresh" | "set-theme" | "set-locale" | "focus" | "destroy"
}

export interface InitializedEventPayload {
  "viewKey": string
  "surfaceType": FlowEmbedSurfaceType
  "capabilities": ReadonlyArray<FlowEmbedCapability>
}

export interface ResizeEventPayload {
  "height": number
}

export interface SelectionChangedEventPayload {
  "selection": ReadonlyArray<HostRecordProjection>
}

export interface FormSavedEventPayload {
  "receiptId": string
  "record": HostRecordProjection
  "clientMutationId": string
}

export interface EmbedBridgeErrorPayload {
  "errorCode": string
  "message": string
  "traceId": string | null
  "recoverable": boolean
  "category"?: "SESSION" | "IDENTITY" | "ORIGIN" | "RESOURCE" | "TRANSIENT" | "UNKNOWN"
  "phase"?: string
  "relaunchRequired"?: boolean
}

export interface SessionExpiredEventPayload {
  "reason": string
  "relaunchRequired": true
}

export interface NavigationRequestEventPayload {
  "target": "LIST" | "CREATE" | "VIEW" | "BACK"
  "recordId": FlowEmbedRecordId | null
}

export interface ActionStartedEventPayload {
  "actionKey": string
  "clientMutationId": string
}

export interface ActionCompletedEventPayload {
  "actionKey": string
  "receiptId": string
  "result": FlowEmbedJsonValue
}

export interface CloseRequestedEventPayload {
  "reason": string
}

export interface FlowEmbedCommandPayloadMap {
  "refresh": Record<string, never>
  "set-theme": { theme: 'light' | 'dark' | 'system' }
  "set-locale": { locale: string }
  "focus": Record<string, never>
  "destroy": Record<string, never>
}

export interface FlowEmbedEventPayloadMap {
  "ack": AckEventPayload
  "initialized": InitializedEventPayload
  "resize": ResizeEventPayload
  "selection.changed": SelectionChangedEventPayload
  "form.saved": FormSavedEventPayload
  "error": EmbedBridgeErrorPayload
  "session.expired": SessionExpiredEventPayload
  "navigation.request": NavigationRequestEventPayload
  "action.started": ActionStartedEventPayload
  "action.completed": ActionCompletedEventPayload
  "close.requested": CloseRequestedEventPayload
}

export type FlowEmbedEventPayload = FlowEmbedEventPayloadMap[keyof FlowEmbedEventPayloadMap]

/** 兼容既有泛型事件消费方；新代码优先使用 FlowEmbedEventFor 或 FlowEmbedTypedEvent。 */
export interface FlowEmbedEvent<T = FlowEmbedEventPayload> {
  protocol: "flow-embed/1"
  type: FlowEmbedEventType
  launchId: string
  channelId: string
  messageId?: string
  requestId?: string | null
  timestamp?: string
  payload?: T
}

export interface FlowEmbedConnectedEvent {
  protocol: "flow-embed/1"
  type: 'connected'
  launchId: string
  channelId: string
}

/** SDK 在握手失败时本地合成；payload 仍严格复用 OpenAPI error Schema。 */
export interface FlowEmbedLocalErrorEvent {
  protocol: "flow-embed/1"
  type: 'error'
  launchId: string
  channelId: string
  payload: EmbedBridgeErrorPayload
}

export type FlowEmbedProtocolEvent<K extends FlowEmbedProtocolEventType = FlowEmbedProtocolEventType> = {
  protocol: "flow-embed/1"
  type: K
  launchId: string
  channelId: string
  messageId: string
  requestId?: string | null
  timestamp: string
  payload: FlowEmbedEventPayloadMap[K]
}

export type FlowEmbedEventFor<K extends FlowEmbedEventType> =
  K extends 'connected'
    ? FlowEmbedConnectedEvent
    : K extends 'error'
      ? FlowEmbedProtocolEvent<'error'> | FlowEmbedLocalErrorEvent
    : K extends FlowEmbedProtocolEventType
      ? FlowEmbedProtocolEvent<K>
      : never

export type FlowEmbedTypedEvent = {
  [K in FlowEmbedEventType]: FlowEmbedEventFor<K>
}[FlowEmbedEventType]

export interface FlowEmbedHeightOptions {
  mode?: 'auto' | 'fixed'
  min?: number
  max?: number
  initial?: number
}

export interface FlowEmbedMountOptions {
  container: { appendChild(node: HTMLIFrameElement): unknown }
  embedUrl: string
  launchId: string
  launchCode: string
  channelId: string
  targetOrigin: string
  protocol?: "flow-embed/1"
  title?: string
  height?: FlowEmbedHeightOptions
  handshakeTimeoutMs?: number
  destroyTimeoutMs?: number
  maxMessageBytes?: number
  maxSeenMessageIds?: number
  onEvent?: (event: FlowEmbedTypedEvent) => void
  onViolation?: (error: FlowEmbedError) => void
}

export class FlowEmbedError extends Error {
  readonly errorCode: string
  constructor(message: string, errorCode?: string, cause?: unknown)
}

export class FlowEmbedWidget {
  readonly launchId: string
  readonly channelId: string
  readonly targetOrigin: string
  readonly embedUrl: string
  refresh(): string
  setTheme(theme: 'light' | 'dark' | 'system'): string
  setLocale(locale: string): string
  focus(): string
  sendCommand<K extends FlowEmbedCommand>(
    type: K,
    ...args: FlowEmbedCommandPayloadMap[K] extends Record<string, never>
      ? [payload?: FlowEmbedCommandPayloadMap[K]]
      : [payload: FlowEmbedCommandPayloadMap[K]]
  ): string
  on<K extends FlowEmbedEventType>(type: K, handler: (event: FlowEmbedEventFor<K>) => void): () => void
  on(type: '*', handler: (event: FlowEmbedTypedEvent) => void): () => void
  off<K extends FlowEmbedEventType>(type: K, handler: (event: FlowEmbedEventFor<K>) => void): void
  off(type: '*', handler: (event: FlowEmbedTypedEvent) => void): void
  destroy(): Promise<void>
  getState(): 'waiting' | 'acknowledging' | 'connected' | 'destroying' | 'failed' | 'destroyed'
}

export function mount(options: FlowEmbedMountOptions): FlowEmbedWidget
export function createSecureNonce(cryptoRef?: Crypto): string
export function normalizeTargetOrigin(value: string): string
export function normalizeEmbedUrl(value: string, targetOrigin: string, launchId: string): string

export const FlowEmbed: Readonly<{ mount: typeof mount }>
export default FlowEmbed
