alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 168h
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        cpu: 200m
        memory: 256Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus-node-exporter:
  enabled: true

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 7d
    retentionSize: 16GB
    resources:
      requests:
        cpu: 250m
        memory: 768Mi
      limits:
        cpu: "2"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
