fullnameOverride: flow-monitoring

defaultRules:
  create: true

alertmanager:
  enabled: false
  alertmanagerSpec:
    replicas: 1
    retention: 24h
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

grafana:
  enabled: true
  admin:
    existingSecret: flow-grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://flow-loki-gateway.flow-observability.svc.cluster.local
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://flow-tempo.flow-observability.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: -5m
          spanEndTimeShift: 5m
          tags:
            - key: service.name
              value: service
            - key: request_id
              value: request_id
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus-node-exporter:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 6h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
