loki:
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16
    retention_period: 168h

singleBinary:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 20Gi
    storageClass: local-path
