tempo:
  retention: 168h
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

persistence:
  enabled: true
  storageClassName: local-path
  size: 20Gi
